### ISSUE TITLE
Very noisy output when port is already free

### ISSUE THREAD

**Issue by kibertoad** [hilleer/kill-port-process#97]
Currently I'm getting this kind of errors when there is nothing to be killed:

```
Failed to get pid of port 3011 Error: Couldn't find a process with port `3011`
    at getPort (C:\sources\node\autopilot\node_modules\pid-from-port\index.js:29:9)
    at C:\sources\node\autopilot\node_modules\pid-from-port\index.js:51:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This is way too much noise. Simple one-liner saying that port wasn't busy to begin with would suffice. Would it be possible to either add a quiet mode for "not found" error, or some ways to customize errors thrown?

**Comment by hilleer** [comment]
Hi @kibertoad 

I never came back to improving this. How would a flag like `--silent` work for you?

**Comment by kibertoad** [comment]
it would be great!

**Comment by hilleer** [comment]
I published a new (beta) version `3.3.1-0` [here](https://www.npmjs.com/package/kill-port-process/v/3.3.1-0).

Would be thankful if you can give it a try when you have time 🤞
